baseURL = "https://slides.matthewselby.com/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Slides by Matthew Selby"
theme = "reveal-hugo"
enableRobotsTXT = true

# had some trouble with hugo multilingual not liking a monolingual site --added taxonomyTerm
disableKinds = ["sitemap", "RSS", "404", "taxonomyTerm", "taxonomy"]

[author]
name = "Matthew Selby"

[params.reveal_hugo]
history = true
custom_theme = "reveal-hugo/themes/robot-lung.css"
margin = 0.2
highlight_theme = "color-brewer"
transition = "slide"
transition_speed = "fast"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
