baseURL = "https://slides.matthewselby.com/"
languageCode = "en-us"
title = "Slides by Matthew Selby"
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"

[author]
name = "Matthew Selby"

[params.reveal_hugo]
history = true
custom_theme = "reveal-hugo/themes/robot-lung.css"
margin = 0.2
highlight_theme = "color-brewer"
transition = "slide"
transition_speed = "fast"

[params.reveal_hugo.templates.hotpink]
class = "hotpink"
background = "#FF4081"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
