baseURL = "https://slides.matthewselby.com/"
languageCode = "en-us"
title = "Slides by Matthew Selby"
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"

[author]
name = "Matthew Selby"

[params.reveal_hugo]
history = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
